services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: secret  # Só precisa desta linha para o root
      MYSQL_DATABASE: lotofacil
      # Remova estas linhas para o usuário root:
      # MYSQL_USER: root
      # MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Monta o script SQL
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lotofacil-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root               # Adicione esta linha
      PMA_PASSWORD: secret         # Adicione esta linha
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge